services:
  conduit-frontend:
    image: ghcr.io/georgstrassberger/conduit-fe:${TAG:-latest}
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     API_HOST: ${API_HOST}
    ports:
      - "8082:80"
    restart: on-failure:3


  conduit-backend:
    image: ghcr.io/georgstrassberger/conduit-be:${TAG:-latest}
    #build:
    #  context: ./conduit-backend
    #  dockerfile: Dockerfile
    ports:
      - "7000:8000"
    env_file:
      - conduit-backend/.env
    restart: on-failure:3
    volumes:
      - backup-data:/app/db/db.sqlite3

volumes:
  backup-data:
