services:
  backend:
    build:
      context: ./conduit-backend
    container_name: conduit-backend
    ports:
      - "7000:8000"
    env_file:
      - ./conduit-backend/.env
    volumes:
     - ./conduit-backend:/app  # optional for Hot-Reload
    restart: on-failure:5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        

  frontend:
    build:
      context: ./conduit-frontend
    container_name: conduit-frontend
    ports:
      - "8082:80"  # Angular via Nginx
    restart: on-failure:5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"