name: Demo Workflow

on:
  push:
    branches:
      - main
      - docker
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0
      - name: ECHO Frontend Build
        run: echo "Building frontend..."
      # Cache node modules
      - name: List files
        run: ./conduit-frontend/ls -la

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0
      - name: ECHO Backend Build
        run: echo "Building backend..."
      # Cache pip modules
      - name: List files
        run: ./conduit-backend/ls -la

  deploy:
    needs:
      - build-frontend
      - build-backend
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Step
        run: echo "Deploying application..."
