name: Demo Workflow

on:
  push:
    branches:
      - main
      - docker
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello World
        run: echo "Hello, World!"
      - name: Checkout repository
        uses: actions/checkout@v5

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Step
        run: echo "Deploying application..."
