name: Demo Workflow

on:
  push:
    branches:
      - main
      - docker
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: ECHO Frontend Build
        run: echo "Building frontend..."

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: ECHO Backend Build
        run: echo "Building backend..."

  deploy:
    needs:
      - build-frontend
      - build-backend
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Step
        run: echo "Deploying application..."
