name: Deploy-Workflow

on:
  push:
    branches:
      - "main"
      - "docker"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Check out code & submodules
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./conduit-frontend
          file: ./conduit-frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/georgstrassberger/conduit-frontend:${{ steps.image_tag.outputs.tag || 'latest' }}

      - name: Build & push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./conduit-backend
          file: ./conduit-backend/Dockerfile
          push: true
          tags: |
            ghcr.io/georgstrassberger/conduit-backend:${{ steps.image_tag.outputs.tag || 'latest' }}

  deploy:
    name: Deploy to Remote Server
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Check out code & submodules
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || '22' }}
          source: "docker-compose.yml"
          target: "${{ secrets.DEPLOY_PATH }}/"

      - name: Pull new images & restart
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || '22' }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            docker compose down --remove-orphans
            docker compose pull
            docker compose up -d
